### ISSUE TITLE
Transcoder.Output() doesn't output progress

### ISSUE THREAD

**Issue by falzm** [xfrr/goffmpeg#54] opened 2020-04-08 18:23 UTC
Hi 👋 

I'm trying to write a small utility that resizes video files while reporting the progress of the transcoding, so using your package I wrote this snippet that works (i.e. the file transcoding works), but no output is streamed from channel returned by the `Transcoder.Output()` method:

```go
package main

import (
	"fmt"

	"github.com/xfrr/goffmpeg/transcoder"
)

var inputPath = "test.mkv"
var outputPath = "test.res.mkv"

func main() {
	trans := new(transcoder.Transcoder)

	err := trans.Initialize(inputPath, outputPath)
	if err != nil {
		panic(err)
	}
	trans.MediaFile().SetAudioCodec("copy")
	trans.MediaFile().SetVideoCodec("libx264")
	trans.MediaFile().SetVideoFilter("scale=854:480")
	trans.MediaFile().SetCRF(18)
	trans.MediaFile().SetPreset("veryslow")

	done := trans.Run(true)
	for msg := range trans.Output() {
		fmt.Println(msg) // <- Nothing printed out here
	}

	if err = <-done; err != nil {
		panic(err)
	}
}
```

I did a bit of digging, and it seems that `bufio.Scanner()` [gets stuck here](https://github.com/xfrr/goffmpeg/blob/master/transcoder/transcoder.go#L315) (no iteration in the loop).

I'm running ffmpeg 4.2.2 on macOS and Go 1.14.0, let me know if you need more information.

**Comment by LuaxY** [comment] 2020-04-20 02:23
Problem seem to be caused by this line:
https://github.com/xfrr/goffmpeg/blob/372fcc37eb107ca77407258f3be6441e4ee708dd/transcoder/transcoder.go#L227

**Comment by manscrober** [comment] 2020-05-06 22:51
I created a pull request removing the line. Errors do still seem to be printed - and it's not like the current code handles these errb in any way. I tried to use it without the line and it very much does work as I would expect it to.

**Comment by falzm** [comment] 2020-05-07 06:00
Thanks @manscrober!

**Comment by falzm** [comment] 2020-07-06 07:02
`wontfix`, seriously?

**Comment by LuaxY** [comment] 2020-07-06 11:35
#61 is already merged

**Closed** 2020-09-11 15:38 UTC
Labels: wontfix
